name: sfs19
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  animator: ^0.1.4
  pie_chart: ^1.0.0
  path_provider: ^0.4.1
  sqflite: ^1.0.0
  url_launcher: ^5.0.3
  fluttertoast: ^3.1.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/gvcc1.png
    - assets/gvcc2.png
    - assets/gvcc3.png
    - assets/gvcc4.png
    - assets/gvcc5.png
    - assets/gcc1.png
    - assets/gcc2.png
    - assets/gcc3.png
    - assets/gcc4.png
    - assets/gcc5.png
    - assets/gcc6.png
    - assets/ncc1.png
    - assets/ncc2.png
    - assets/ncc3.png
    - assets/nvcc1.png
    - assets/nvcc2.png
    - assets/nvcc3.png
    - assets/nvcc4.png
    - assets/tacc1.png
    - assets/tacc2.png
    - assets/tacc3.png
    - assets/tacc4.png
    - assets/tacc5.png
    - assets/tacc6.png
    - assets/tavc1.png
    - assets/tavc2.png
    - assets/tavc3.png
    - assets/tavc4.png
    - assets/tavc5.png
    - assets/tcc1.png
    - assets/tcc2.png
    - assets/tcc3.png
    - assets/tcc4.png
    - assets/tvc1.png
    - assets/tvc2.png
    - assets/tvc3.png
    - assets/tvc4.png
    - assets/tvc5.png
    - assets/tvc6.png
    - assets/ght.png
    - assets/tht.png
    - assets/taht.png
    - assets/nht.png
    - assets/emblem.JPG
    - assets/head.png
    - assets/mepic.png




  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
